### ISSUE TITLE
Running `installOpenCV()` overwrites {opencv} package

### ISSUE THREAD

**Issue by JamesM131** [swarm-lab/ROpenCVLite#25]
I have been using the {opencv} package from ropensci (https://github.com/ropensci/opencv/). I noticed that when I use this package (to facilitate access to {Rvision}), the standalone {opencv} package will be overwritten. After reinstalling the {opencv} package I am then required to run the `installOpenCV()` function to enable {Rvision}. 

It looks like the two packages are writing to the same location. This could be confusing as these packages deal with very similar problem sets and users are likely to experiment with them both. It may make more sense to write to a more specific directory that isn't likely to have a name clash. 

I am running this on macOS 12.3.1 and R 4.1.0.

**Comment by sjmgarnier** [comment]
@JamesM131 That's a good catch, I never thought about that. I can easily change the installation directory in the next update. I was actually thinking of adding an option to specify a custom installation directory, so that would be a good motivation to finally implement that. I just pushed the latest update of ROpenCVLite to CRAN, so that might take some time before I push the next one.

**Comment by sjmgarnier** [comment]
@JamesM131 Actually, it took less time than I imagined. You can try the new version on the repository (4.55.1). I will not push it to CRAN before several weeks because I haven't had the time to fully test it.
